name: Update BMW Leaderboard

on:
  schedule:
    - cron: "0 13-23 * * *"
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("dplyr", "golfastr"), repos="https://cloud.r-project.org")'

      - name: Configure Git
        run: |
          git config user.name "leaderboard-bot"
          git config user.email "actions@github.com"

      - name: Update leaderboard every minute
        run: |
          END=$((SECONDS + 340*60))

          while [ $SECONDS -lt $END ]; do

            echo "Updating leaderboard..."
            Rscript script_for_updates.R

            git add data/tls_leaderboard_data.rds

            if git diff --cached --quiet; then
              echo "No change to leaderboard."
            else
              git commit -m "Update leaderboard"
              git push
            fi

            sleep 60
          done
