name: Update BMW Leaderboard

on:
  schedule:
    - cron: "0 13-23 * * *"
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages("dplyr", repos="https://cloud.r-project.org")'
          Rscript -e 'install.packages("golfastr", repos="https://cloud.r-project.org")'

      - name: Configure Git
        run: |
          git config user.name "leaderboard-bot"
          git config user.email "actions@github.com"

      - name: Test files
        run: |
          echo "WHERE AM I?"
          pwd

          echo "WHAT FILES ARE HERE?"
          ls -la

          echo "DOES THE SCRIPT EXIST?"
          ls -la script_for_updates.R

      - name: Update leaderboard
        run: |
          Rscript script_for_updates.R
